model:
  model: 'PINO'
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]

data:
  dataset: 'KMFlow'
  data_path: '../data/fluid/ns_2d/NS-Re500_T300_id0-shuffle.npy'
  raw_resolution: [256, 256, 513]
  sample_resolution: [64, 64, 257]
  pde_resolution: [256, 256, 513]
  eval_resolution: [256, 256, 513]
  start_x: 0
  end_x: 1
  start_y: 0
  end_y: 1
  t: 1.0
  split_factor: 2
  Re: 500
  train_ratio: 0.6
  valid_ratio: 0.2
  test_ratio: 0.2
  subset: False
  subset_ratio: 0.5

train:
  random_seed: 2020
  cuda: True
  device: 5
  epochs: 1000
  patience: 10
  eval_freq: 10
  train_batchsize: 20
  saving_checkpoints: False
  saving_best: True
  data_weight: 1000.0
  f_weight: 0.1
  ic_weight: 0.0

eval:
  eval_batchsize: 1
  eval_resolution: [256, 256, 513]
  visualize: True
  heatmap: True
  movie: True

optimize:
  optimizer: 'Adam'
  lr: 0.002
  weight_decay: 0.0001
  momentum: 0.95
  milestones: [200, 400, 600]
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
