model:
  model: 'PINO'
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  width: 64
  act: gelu
  num_pad: 4

data:
  dataset: 'Burgers'
  data_path: '../data/fluid/burgers/burgers_pino.mat'
  start_x: 0
  end_x: 1
  t: 1
  raw_resolution: [128, 101]
  sample_resolution: [128, 101]
  v: 0.01
  train_ratio: 0.6
  valid_ratio: 0.2
  test_ratio: 0.2
  subset: False
  subset_ratio: 0.1

train:
  random_seed: 2020
  cuda: True
  device: 4
  epochs: 500
  patience: 10
  eval_freq: 5
  train_batchsize: 50
  saving_checkpoints: False
  saving_best: True
  data_weight: 0.0
  f_weight: 1.0
  ic_weight: 10.0

eval:
  eval_batchsize: 1
  eval_resolution: [128, 101]
  visualize: True
  heatmap: True
  movie: True

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0001
  momentum: 0.95
  milestones: [200, 400]
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: True
  wandb_project: 'Fluid'
